import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { REPO_ROOT } from './lib/paths';

const SPECS_DIR = resolve(REPO_ROOT, 'docs/superpowers/specs');
const OUT_JSON = resolve(REPO_ROOT, 'docs/testing/requirements-index.json');
const OUT_MD = resolve(REPO_ROOT, 'docs/testing/requirements-index.md');
const MARKER = /^- <a id="(rq-[a-z]+-\d{3})"><\/a>\s*(RQ-[A-Z]+-\d{3}):\s*(.+)$/;

interface Requirement {
  id: string;
  title: string;
  spec: string;
  anchor: string;
}

const requirements: Requirement[] = [];

for (const file of readdirSync(SPECS_DIR).filter((entry) => entry.endsWith('.md')).sort()) {
  const lines = readFileSync(join(SPECS_DIR, file), 'utf8').split('\n');
  for (const line of lines) {
    const match = MARKER.exec(line.trim());
    if (match) {
      requirements.push({
        id: match[2],
        title: match[3].trim(),
        spec: `docs/superpowers/specs/${file}`,
        anchor: match[1],
      });
    }
  }
}

const seen = new Set<string>();
for (const requirement of requirements) {
  if (seen.has(requirement.id)) throw new Error(`Duplicate requirement id ${requirement.id}`);
  seen.add(requirement.id);
}

mkdirSync(resolve(REPO_ROOT, 'docs/testing'), { recursive: true });
writeFileSync(
  OUT_JSON,
  `${JSON.stringify({ schemaVersion: 1, generatedFrom: 'docs/superpowers/specs/*.md', requirements }, null, 2)}\n`,
);

const markdown = [
  '# Requirements Index',
  '',
  'Generated by `e2e/scripts/build-requirements-index.ts`. Do not hand-edit.',
  '',
  '| ID | Title | Spec |',
  '|---|---|---|',
  ...requirements.map(
    (requirement) => `| ${requirement.id} | ${requirement.title} | [${basename(requirement.spec)}#${requirement.anchor}](${requirement.spec}#${requirement.anchor}) |`,
  ),
].join('\n');
writeFileSync(OUT_MD, `${markdown}\n`);

console.log(`build-requirements-index: ${requirements.length} requirement(s)`);
